
https://lp3test.polskieradio.pl/Article/GetListByCategoryId?categoryId=4090&PageSize=100&skip=0&format=400
X-Api-Key: f2d29c85-ab02-4cee-ba4f-403c5f8f344d

###

https://trojka.polskieradio.pl/_next/data/XI7_XRohC52yvsJhLJ5FP/artykul/2419484%2CTony-z-betonu-10-grudnia-godz-1509.json
X-Api-Key: f2d29c85-ab02-4cee-ba4f-403c5f8f344d

####

https://trojka.polskieradio.pl/_next/data/XI7_XRohC52yvsJhLJ5FP/artykul/2415177,Tony-z-betonu-3-grudnia-godz-1509.json
X-Api-Key: f2d29c85-ab02-4cee-ba4f-403c5f8f344d
